### ISSUE TITLE
Create Article Worktype

### ISSUE THREAD

**Issue by julesies** [UNC-Libraries/blacklight_oai_provider#2]
This is work in support of project, but not directly for this OAI GEM
Done Looks Like:

Worktype is available in hyrax test system for Article
Worktype is modeled after current MD practices
Worktype has at least one different field than Article Worktype

Please note: these worktypes just need to show that we can pass the kind of information we need to pass. These do not need to be set in stone or exact.

**Comment by julesies** [comment]
For now Duke and UNC can/should? use the same fields for worktypes for testing and comparison purposes. It might make sense for Duke to do the Article and UNC to do the Dissertation?

**Comment by seanaery** [comment]
@julesies I agree it'd be helpful at this stage -- where the focus is on getting OAI-PMH in place -- to try to use the same fields and worktypes between Duke & UNC. Seems likely that longer-term we'd have some differences.
